---
title: "Compare"
author: "Alan n. Inglis"
date: "`r Sys.Date()`"
output:
  pdf_document: default
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE,  fig.width = 5, fig.height = 5, fig.align = "center", fig.path = "compareFigs/", fig.show='hold')
```

## Load libraries:

```{r load_libraries}
library(dbarts) # for model
library(bartMan) # for visualizations
library(vivid) # for agnostic visualizations
library(ggplot2) # for visualizations

   
```

## Read in and setup data:

```{r create_data}
# Create some data
f <- function(x) {
  10 * sin(pi * x[, 1] * x[, 2]) + 20 * (x[, 3] - 0.5)^2 +
    10 * x[, 4] + 5 * x[, 5]
}


set.seed(1701)
sigma <- 1.0
n <- 250
x <- matrix(runif(n * 10), n, 10)
colnames(x) <- paste0("x", 1:10)
Ey <- f(x)
y <- rnorm(n, Ey, sigma)
fData <- as.data.frame(cbind(x, y))

x <- fData[, 1:10]
y <- fData$y

```

## Build models

```{r build_all_models}
set.seed(1701)
dB20 <- bart(x.train = x,
             y.train = y,
             ntree = 20,
             keeptrees = TRUE,
             nskip = 100,
             ndpost = 1000
)

set.seed(1701)
dB100 <- bart(x.train = x,
              y.train = y,
              ntree = 100,
              keeptrees = TRUE,
              nskip = 100,
              ndpost = 1000
)

set.seed(1701)
dB200 <- bart(x.train = x,
              y.train = y,
              ntree = 200,
              keeptrees = TRUE,
              nskip = 100,
              ndpost = 1000
)


```

## Create dataframe of trees

```{r extractTrees_20}
dbT20 <- extractTreeData(model = dB20, data = fData)
```

```{r extractTrees_100}
dbT100 <- extractTreeData(model = dB100, data = fData)
```

```{r extractTrees_200}
dbT200 <- extractTreeData(model = dB200, data = fData)
```





## Figure 11:
# 20 trees
```{r vivi_vsup_20}
# Set var order
newOrder <- c("x1","x2","x3","x4","x5", 'x6', 'x7', 'x8', 'x9', 'x10')

# vsup matrix
vsupMat <- viviBartMatrix(dbT20, type = 'vsup', metric = 'propMean', 
                          metricError = "CV", reorder = F)

# reorder
vsupMat$actualMatrix <- vsupMat$actualMatrix[newOrder,newOrder]
vsupMat$uncertaintyMatrix <- vsupMat$uncertaintyMatrix[newOrder,newOrder]


colors <- scales::colour_ramp(
  colors = c(blue = '#FFFFCC', red = '#800026')
)((0:7)/7)

newCols <- RColorBrewer::brewer.pal(9, 'GnBu')
colors2 <- newCols[-1]


# -------------------------------------------------------------------------

vivid::viviHeatmap(vsupMat$actualMatrix,
                   intPal = colors,
                   impPal = colors2)  



# plot vsup
viviBartPlot(vsupMat,
             intPal = colors,
             impPal = colors2,
             max_desat = 1, 
             pow_desat = 0.6, 
             max_light = 0.6,
             pow_light = 1, 
             label = "CV"
             ) +
  theme(axis.text.x = element_text(hjust = 0.5))
```

## vivid for 20 trees
```{r vivid_20}

response = 'y'
data = fData
# create predict function
responseIdx <- which(colnames(data) == response)
pFun <- function(fit, data, prob=TRUE) apply(predict(fit, data[,-responseIdx]), 2, mean)


# run vivid
set.seed(1701)
mat <- vivid::vivi(fit = dB20,
                   data = fData,
                   response = 'y',
                   reorder = F,
                   gridSize = 10,
                   nmax = 500,
                   normalized = FALSE,
                   class = 1,
                   predictFun = pFun)

mat <- mat[newOrder,newOrder]
viviHeatmap(mat,
            intPal = colors,
            impPal = colors2)


```

# 100 trees
```{r vivi_vsup_100}
# Set var order
newOrder <- c("x1","x2","x3","x4","x5", 'x6', 'x7', 'x8', 'x9', 'x10')

# vsup matrix
vsupMat <- viviBartMatrix(dbT100, type = 'vsup', 
                          metric ='propMean',  
                          metricError = "CV", reorder = F)

# reorder
vsupMat$actualMatrix <- vsupMat$actualMatrix[newOrder,newOrder]
vsupMat$uncertaintyMatrix <- vsupMat$uncertaintyMatrix[newOrder,newOrder]


colors <- scales::colour_ramp(
  colors = c(blue = '#FFFFCC', red = '#800026')
)((0:7)/7)

newCols <- RColorBrewer::brewer.pal(9, 'GnBu')
colors2 <- newCols[-1]


# -------------------------------------------------------------------------

vivid::viviHeatmap(vsupMat$actualMatrix,
                   impLims = c(0, 0.16),
                   intPal = colors,
                   impPal = colors2) 


# plot vsup
viviBartPlot(vsupMat,
             intPal = colors,
             impPal = colors2,
             impLims = c(0, 0.16),
             max_desat = 1, 
             pow_desat = 0.6, 
             max_light = 0.6,
             pow_light = 1, 
             label = "CV"
             ) +
  theme(axis.text.x = element_text(hjust = 0.5))
```

## vivid for 100 trees
```{r vivid_100}

response = 'y'
data = fData
# create predict function
responseIdx <- which(colnames(data) == response)
pFun <- function(fit, data, prob=TRUE) apply(predict(fit, data[,-responseIdx]), 2, mean)


# run vivid
set.seed(1701)
mat <- vivid::vivi(fit = dB100,
                   data = fData,
                   response = 'y',
                   reorder = F,
                   gridSize = 10,
                   nmax = 500,
                   normalized = FALSE,
                   class = 1,
                   predictFun = pFun)

mat <- mat[newOrder,newOrder]
viviHeatmap(mat,
            intPal = colors,
            impPal = colors2)


```

# 200 trees
```{r vivi_vsup_200}
# Set var order
newOrder <- c("x1","x2","x3","x4","x5", 'x6', 'x7', 'x8', 'x9', 'x10')

# vsup matrix
vsupMat <- viviBartMatrix(dbT200, type = 'vsup', 
                          metric ='propMean',  
                          metricError = "CV", reorder = F)

# reorder
vsupMat$actualMatrix <- vsupMat$actualMatrix[newOrder,newOrder]
vsupMat$uncertaintyMatrix <- vsupMat$uncertaintyMatrix[newOrder,newOrder]


colors <- scales::colour_ramp(
  colors = c(blue = '#FFFFCC', red = '#800026')
)((0:7)/7)

newCols <- RColorBrewer::brewer.pal(9, 'GnBu')
colors2 <- newCols[-1]


# -------------------------------------------------------------------------

vivid::viviHeatmap(vsupMat$actualMatrix,
                   impLims = c(0, 0.14),
                   intPal = colors,
                   impPal = colors2) 


# plot vsup
viviBartPlot(vsupMat,
             intPal = colors,
             impPal = colors2,
             impLims = c(0, 0.14),
             max_desat = 1, 
             pow_desat = 0.6, 
             max_light = 0.6,
             pow_light = 1, 
             label = "CV"
             ) +
  theme(axis.text.x = element_text(hjust = 0.5))
```

## vivid for 200 trees
```{r vivid_200}

response = 'y'
data = fData
# create predict function
responseIdx <- which(colnames(data) == response)
pFun <- function(fit, data, prob=TRUE) apply(predict(fit, data[,-responseIdx]), 2, mean)


# run vivid
set.seed(1701)
mat <- vivid::vivi(fit = dB200,
                   data = fData,
                   response = 'y',
                   reorder = F,
                   gridSize = 10,
                   nmax = 500,
                   normalized = FALSE,
                   class = 1,
                   predictFun = pFun)

mat <- mat[newOrder,newOrder]
viviHeatmap(mat,
            intPal = colors,
            impPal = colors2)


```






